app/pnpm-lock.yaml
app/src/components/NotificationToast.tsx
app/src/hooks/useChains.tsx
app/src/hooks/usePastTransfers.tsx
app/src/hooks/useTokens.tsx
app/src/models/notification.ts
app/src/models/transfer.ts
app/src/services/chains.ts
app/src/services/pastTransfers.ts
app/src/store/notificationStore.ts

This PR
- adds `useChains` and `usePastTransfers` hooks
- adds `chains` and `pastTransfers` services
- adds first draft of `transfer` model
- adds `useTokens` template that still needs to be implemented. As well as `tokens` service.
Note: To keep the PR smaller I will include `useOngoingTransfers`, `useTransfer` etc. in separat PRs.

Add hooks and services

---

app/src/__tests__/Transfer.test.tsx
app/src/__tests__/testdata.ts
app/src/components/Transfer.tsx
app/src/hooks/useTransfer.tsx
app/src/models/token.ts
app/src/services/transfer.ts
app/src/utils/transfer.ts

Currently the app expects the input amount to be already provided with the right decimal base for the selected token.
In this PR, we change that so the user provides a user-facing amount (e.g. 1 WETH) and we convert it to the right decimal base for the selected token.
- Add `decimals` field to the `Token` type
- Convert the input amount to the right value using `convertAmount`
- Add unit tests

fix: Convert amount to right decimal base

---

app/src/components/ChainSelect.tsx
app/src/hooks/useLookupName.tsx

This PR contains 
- an improvement of the **useLookupName** to support initialization with **null** values. 
- a small refactoring of fetch ens names from the **Chain Select** fetching component to rely on the useLookupName hook. It should **handle address & network changes to prevent rendering issues. 🤞**
**However:** I have not been able to reproduce the known issue from the mainnet. This PR needs testing on Mainnet as I do not own any ENS for my addresses on Eth mainnet. Tests have been made on Sepolia using a different provider. 
In case the issue is still here, we should consider updating the provider.

refacto ens fetch on transfer component

---

app/src/app/globals.css
app/src/components/TokenAmountSelect.tsx
app/src/components/Transfer.tsx
app/src/hooks/useTransferForm.tsx
app/src/models/select.ts

Show current balance for selected token And tweak input styling more according to the figma specs.
NOTE: This is a temporary design solution until Brandon designs it.
A. No selected token
B. Selected token with balance
C. Selected token without balance

ad-hoc: Show current balance for selected token

---

app/src/hooks/useSnowbridgeTransferEstimate.tsx

It persists the progressBar data using the available cache and removes the lag between the transfer card and the dialog.

fix: persist progressbar data

---

app/src/components/completed/TransactionDialog.tsx
app/src/components/completed/TransactionHistory.tsx

Currently, the issue is the following: 
On the first load of an ongoing or completed transfer from localstorage, they are not serialized while after a refresh of the app, the localstorage serialized dates from Date type to string. 
This fix should support the formatting of both formats as it now converts the date into an ISO format.

fix: invalid date on first load

---

app/src/components/HomeComponentSelect.tsx
app/src/components/Transfer.tsx

Fixes https://linear.app/velocitylabs/issue/VEL-60/preserve-transfer-form-state-when-switching-to-completed-transfers
Basically, instead of rendering or removing the form and ongoing txs components based on the selected tab, we show or hide it, respectively.

fix: Preserve Transfer form state on menu tab switch

---

app/src/components/HomeComponentSelect.tsx

Fixes https://linear.app/velocitylabs/issue/VEL-62/fix-completed-transfers-are-displayed-under-the-transfer-component

Fix completed txs showing on New tab

---

app/src/app/api/history/route.ts
app/src/components/OngoingTransfers.tsx
app/src/hooks/useOngoingTransfersTracker.tsx
app/src/utils/snowbridge.ts
app/src/utils/subscan.ts
app/src/utils/transferTracking.ts

This PR contains the first part of the transfer tracking cleaning & improvements. 
_No big logic change._ Transfers from a Parachain to Eth or AH do not rely on Snowbridge API anymore but on the Subscan direct XCM queries. Eth to Parachain/AH transfers still rely on Snowbridge API since this is the best approach. 
This first part contains a lot of files moved to a snowbridge agnostic file. _Some tests will be conducted once Bifrost to AH transfers are supported to get rid of the `const transfers: OngoingTransfers` in the history/route._
- a new utils/transfersTracking.ts that handles transfers depending on direction through `trackTx()` fn.
- utils/snowbridge.ts or utils/subscan.ts helpers (such as getErrorMessage(), getTransferStatus()…) moved to the new utils/transfersTracking.ts file.
- …

improvement: transfer tracking cleaning

---

app/src/components/completed/TransactionDialog.tsx
app/src/hooks/useOngoingTransfers.tsx
app/src/hooks/useOngoingTransfersTracker.tsx
app/src/models/transfer.ts
app/src/store/ongoingTransfersStore.ts
app/src/utils/transfer.ts

This PR Support displaying tracking through the XCM transfers Subscan Relaychain tracking page: 
- add ongoingTransfer Store method to update the UniqueId
- optional param addition to StoredTransfer type
- implement explorer link in getExplorerLink when uniqueId is available.

improvement: explorer link update

---

app/pnpm-lock.yaml
app/src/components/completed/TransactionDialog.tsx
app/src/hooks/useAssetTransferApi.tsx
app/src/utils/subscan.ts

This PR fix the following: 
- The transfer data handling within the AT API callback: switch transfer result status check from isInBlock to isFinalized. It should prevent registering a first bunch of data that changes once block data is finalized.
- Fixes Subscan, exiting loop too early when an ongoing transfer fails.

fix: transfer data callback handler & subscan loop

---

app/src/components/Credits.tsx

fix: Simplify credits by removing logos

---

app/package.json
app/pnpm-lock.yaml
app/src/__tests__/Transfer.test.tsx
app/src/components/Transfer.tsx
app/src/config/registry.ts
app/src/hooks/useFees.tsx
app/src/hooks/useParaspellApi.tsx
app/src/hooks/useTransferForm.tsx
app/src/utils/paraspell.ts
app/src/utils/transfer.ts

This PR
- adds Paraspell xcm fee fetching
- adds debounce to fetching fees.
- adds DOT transfers from AH to relay and back
- refactors useFees a bit
Future improvements:
- possibly replace `getTransferInfo` with `getOriginFeeDetails` when available. Could be faster

feat ⚡ integrate paraspell xcm fee preview + add relay <-> AH route

---

app/src/models/subscan.ts
app/src/utils/subscan.ts
app/src/utils/transferTracking.ts

- Add a condition to subscan query since finding transfer by extrinsic_id can only work for relaychain
- Switch subscan status definition from cross_chain_status param to status param
- Fix getTransferStatus helper

fix: update tracking status

---

app/package.json
app/pnpm-lock.yaml
app/src/hooks/useFees.tsx
app/src/registry/mainnet.ts
app/src/utils/paraspell.ts

Minimal changes, basically just bumping the dependency and dropping the edge case for AH as a destination chain.
It fixes loading feed and submitting txs destined to Asset Hub.

chore: Update to Paraspell 7.2.0

---

app/src/components/Transfer.tsx
app/src/components/TxSummary.tsx
app/src/hooks/useFees.tsx
app/src/hooks/useParaspellApi.tsx
app/src/hooks/useSnowbridgeApi.tsx
app/src/hooks/useTokenPrice.tsx
app/src/registry/mainnet.ts

Implement cached token price fetch in: 
- useFees
- useSnowbridgeApi
- useParaspellApi
And support allowanceLoading checks before displaying the TxSummy component to avoid overlaps. 
Every call to goingecko API is now cached globally.

Improvement: get token price

---

app/src/components/OngoingTransferDialog.tsx
app/src/components/TokenAmountSelect.tsx
app/src/components/Transfer.tsx
app/src/components/completed/TransactionDialog.tsx
app/src/utils/transfer.ts

- Improve `formatAmount` settings for better results 
- Fix maximum/minimum fraction & significant digits settings
- Set rounding to `floor` to not show values above the real amounts
- apply `formatAmount` on the `TokenAmountSelect` input value **
When applying the `Max` button, sometimes the value was extremely long and overflows the available space:

Improve `formatAmount` and apply it on amount input

---

app/src/app/globals.css
app/src/components/Delayed.tsx
app/src/components/Transfer.tsx
app/src/components/TxSummary.tsx

Improve the fees loading UI and UX:
- Add mini header "Loading fees" - otherwise users have no idea what they are waiting for
- Add a little emphatic and help tagline if it's taking too long
Eventually we want to redesign this but this feel - to me - like a small quick improvement for v2.
(This demo was tweaked so that the fees kept loading if the amount == 5) 
https://github.com/user-attachments/assets/e7e9839c-dd33-4cac-b9c1-de1f2de767f4

Improve fees loading

---

site/src/components/header.tsx

So that clicking anywhere on the button triggers navigation to the website.
I bumped into this a couple times and thought the button was broken. Also removed the `<button>` tag, because we can't nest a button within an `<a>` anchor tag if we want it to be valid HTML5.
Problem:
https://github.com/user-attachments/assets/d0e7c6eb-04e1-4d5a-83d8-0c6a83f5eb92
After the fix:
https://github.com/user-attachments/assets/46c65632-4008-4af4-8355-e7c859a0b8a8

Make Transfer button click-area bigger

---

app/src/hooks/useSnowbridgeApi.tsx
app/src/utils/env.ts

We don't want txs from devs testing locally to end up in the stats.
For reference: https://vercel.com/docs/projects/environment-variables/system-environment-variables#VERCEL_ENV.

fix: Track transactions only on production

---

app/src/components/ChainSelect.tsx
app/src/components/Transfer.tsx
app/src/hooks/useTransferForm.tsx
app/src/registry/mainnet.ts
app/src/utils/address.ts

Fixes https://linear.app/velocitylabs/issue/VEL-165/fix-error-when-trying-to-load-fees-with-an-invalid-dest-addr
When the dest address is set to manual and it's invalid, the app keeps trying to fetch fees the fees and it of course keeps failing and keeps piling up on error notifications:
We also fix the design for the error state, making the input content reddish too.

fix: Prevent fetching fees with an invalid manual address

---

app/src/components/OngoingTransfers.tsx
app/src/hooks/useTransferForm.tsx

This PR fixes a bug where it wasn't scrolled down to ongoing transfers correctly.

fix: scroll down on transfer initiation

---

app/src/components/Account.tsx

add fallback account icon when no addressType is available: 
vs: 
(We can't stay without default icon or the list will be weird with some empty icons on some cards/modal)
@NunoAlexandre I let you tweak the gradients' colors if you do not like them :)

fix: default account icon

---

app/src/components/Tooltip.tsx
app/src/components/Transfer.tsx
app/src/components/TxSummary.tsx

Add duration tooltip for XCM transfers in the TxSummary component.

feat: add duration tool tip for xcm transfers

---

app/src/components/Transfer.tsx
app/src/hooks/useBalance.tsx
app/src/hooks/useTransferForm.tsx

This PR replaces our 95% quick fix for showing balances with the correct amount that is now fetchable via Paraspell.

improvement ⚡ show precise available balance

---

app/src/components/TxSummary.tsx

This PR adds a warning that the snowbridge fees are only for its service and not eth gas costs.
Changed also the label Fee to Bridging Fee for such transfers.

improvement ⚡ Add snowbridge fee warning

---

app/sentry.client.config.ts

This PR removes some unnecessary mask on sentry replay recordings.

fix: unmask sentry replay

---

app/src/registry/mainnet/tokens.ts

This fixs the fetch API error. [See issue](https://linear.app/velocitylabs/issue/VEL-221/fix-token-price-endpoint-500-error)

fix: add coingeckoId to the TON token

---

app/src/components/Transfer.tsx
app/src/hooks/useFees.tsx
app/src/hooks/useTransferForm.tsx
app/src/utils/address.ts

This PR adds some tricks to show the txSummary faster. It uses fallback addresses to fetch fees if no addresses are inputed yet. After they are inputed it refetches the fees to be correct.
Closes VEL-197

improvement: faster tx summary showing

---

app/src/utils/env.ts

When "Automatically expose System Environment Variables" is enabled in Vercel, all env variables have to be prefixed by `NEXT_PUBLIC_`. [Source](https://github.com/vercel/next.js/discussions/45802#discussioncomment-9022511).

fix: fix isPreview and isProduction util functions

---

app/src/hooks/useParaspellApi.tsx
app/src/hooks/useSnowbridgeApi.tsx
app/src/utils/paraspell.ts

This PR
- adds automatic dry run when available for xcm transfers
Design Decisions
- If no dry run is available we treat it as if it has succeeded
- The dry run returns precise xcm fees. But we run the dry run after the form was filled out and immediately before the tx-sign popup appears. So I decided to not use those fees for now. Alternatively, we can explore running the dry run as part of fetching the fees in txSummary. I would prefer to do that in a seperate PR tho.

feat: add xcm dry run api

---

app/package.json
app/pnpm-lock.yaml
app/src/hooks/useOngoingTransfersTracker.tsx
app/src/utils/ocelloids.ts
app/src/utils/transfer.ts

It contains Ocelloids last version which fixes unsupported and missing tracking paths: 
- DOT btw Parachains
- PHA transfers
And includes: 
- Removing unused helpers
- Removing ongoing transfer filters

fix: ocelloids upgrade

---

app/src/components/ChainSelect.tsx
app/src/components/Transfer.tsx
app/src/components/svg/Cross.tsx
app/src/models/select.ts
app/src/utils/sort.ts

This PR
- reorders chains and tokens so the selected one is at the top in the dropdown
- enables clearing capability. I only enabled it for the dest chain as it only makes sense there.
Fixes VEL-224

feat: reorder chains/tokens and add clear button

---

app/src/hooks/useTransferForm.tsx

Fixes the unexpected fee triggers on source chain changes. 
_**To reproduce the issue in production:**_
- Select a between parachains transfers ex: AH => USDC => Bifrost. 
- Update source chain to Eth. 
- The fees are triggered with the wrong data throwing an error.

fix: unexpected fee triggers on source chain changes

---

app/src/components/ActionBanner.tsx
app/src/components/Transfer.tsx
app/src/components/TxSummary.tsx
app/src/hooks/useErc20Allowance.tsx

This PR fixes the USDT allowance issue. 
The USDT smart contract first requires the revoke of the current allowance before setting the new one. 
**It's a two-signature process.** 
I added the following extra info when needed:

fix: usdt revoke allowance

---

app/src/app/api/history/route.ts
app/src/hooks/useTransferProgress.tsx
app/src/store/completedTransfersStore.ts
app/src/utils/transferTracking.ts

This PR fixes the one-click transfer tracking flow. 
_To be noted, the last Hydration direct transfer to ETH took 3h30 against the 1.5 hours estimation we display._

fix: one-click transfer tracking flow

---

app/src/hooks/useFees.tsx
app/src/hooks/useSnowbridgeApi.tsx
app/src/hooks/useSnowbridgeContext.tsx
app/src/models/snowbridge.ts
app/src/registry/mainnet/routes.ts
app/src/utils/snowbridge.ts

We get caching and unify both in one intersected type so that we don't have to keep track of two hooks and two values around the codebase. We might want to cache this server side in the future but for now caching client side for 12 hours should be fine.

imp: Move sb registry instantiation to `useSnowbridgeContext`

---

app/src/hooks/useSnowbridgeApi.tsx
app/src/hooks/useTransferForm.tsx
app/src/utils/snowbridge.ts

Fixes https://velocity-labs.sentry.io/issues/29823189/replays/
Basically validate the transfer before going ahead with estimating execution fees which fails if the tx is invalid.

fix: Validate SB-based transfers before estimating execution fees

---

app/src/app/error.tsx
app/src/app/global-error.tsx
app/src/app/not-found.tsx
app/src/components/Button.tsx
app/src/components/Dropdown.tsx
app/src/components/NotificationToast.tsx
app/src/components/SubstrateWalletModal.tsx
app/src/components/TokenAmountSelect.tsx
app/src/components/Tooltip.tsx
app/src/components/Transfer.tsx
app/src/components/TurtlesBackground.tsx
app/src/components/TxSummary.tsx
app/src/components/WalletButton.tsx

This PR addresses a potential performance issue by removing inline object literals from component props.
Inlining object literals as props (like `<Component data={{key: value}}/>`) creates a new object instance on every render because JavaScript compares objects by reference, not value. This causes:
1. Unnecessary re-renders: Components using React.memo or PureComponent will re-render even when the actual data hasn't changed.
2. Increased memory usage: Each render creates new object instances that must be garbage collected.
3. Reduced performance: Additional rendering cycles and garbage collection affect application speed.
The same issue occurs when inlining functions `<Button onClick={() => handleClick()}/>` or other components as props `<TabPanelheader={<CustomHeader title="Dashboard" …

Remove inline object literals from components props

---

app/src/utils/paraspellSwap.ts

The currencyTo needed special treatment before as it couldn't use parapsells token id. This PR makes the destination token use the multilocation or symbol now as well.

impr: make currencyTo use multilocation as well

---

app/src/registry/mainnet/chains.ts

Addressing a message we got to update these two endpoints
> Hi !
> 
> I'm reaching out because I noticed you are still using one or more of our old endpoints where a new one is available (using the new ones should, in general, lead to better stability and performance).
> 
> 
> Moonbeam
> Old endpoint: [api-moonbeam.dwellir.com](http://api-moonbeam.dwellir.com/) (Usage: Past 30d: 99,645; Past 7d: 33,160; > Past 24hrs: 9,460)
> New endpoint: [api-moonbeam.n.dwellir.com](http://api-moonbeam.n.dwellir.com/) (Usage: 0)
> Polkadot
> Old endpoint: [api-polkadot.dwellir.com](http://api-polkadot.dwellir.com/) (Usage: Past 30d: 505,304; Past 7d: 282,995; > > Past 24hrs: 253,633)
> New endpoint: [api-polkadot.n.dwellir.com](http://api-polkadot.n.dwellir.com/) (Usage: 0)
> 
> Over the coming …

chore: Update Relay & Moonbeam's dwellir endpoints

---

app/src/hooks/useTransferForm.ts

While working on [this PR](https://github.com/velocitylabs-org/turtle/pull/332), I noticed a couple of improvements in the useTransferForm.ts file:
•	Updated the dependency arrays in useCallback hooks to ensure consistent reactivity and avoid unnecessary re-renders.
•	Adjusted the import path for formatAmount to use an absolute path, improving consistency across the codebase.

Refactor useTransferForm dependencies for optimized reactivity

---

app/src/components/ProgressBar.tsx

While working on https://github.com/velocitylabs-org/turtle/pull/332, I noticed an improvement in the `ProgressBar` component. When the `outlinedProgressBar` prop was set to true, the animation (the width transition effect) was not functioning. This fix resolves that issue.

Fix animation and transition effects in ProgressBar

---

app/jest.config.ts
app/jest.setup.ts
app/package.json
app/src/__tests__/Transfer.test.tsx
app/tsconfig.json

There was a failing test with the following error: 
```
Cannot find module '@paraspell/xcm-router' from 'src/utils/paraspellSwap.ts'
```
Apparently the compiler was failing to map the module for some reason. Mapping the module seems to fix the error, but it's still unknown why it wouldn't be mapped in the first place, maybe there's a mistake in the `@paraspell/xcm-router` `package.json`

Fix failing unit test

---

app/package.json
app/pnpm-lock.yaml

Fixes some bugs like an issue stopping users from sending DOT from Bifrost to AssetHub

chore: Bump paraspell to v8.9.10

---

app/src/components/ChainTokenSelect.tsx
app/src/components/Transfer.tsx
app/src/hooks/useFees.ts
app/src/hooks/useTransferForm.ts

I was going through the new swap UI and noticed a couple of things:
1. We’re currently showing the divider for the destination token, even though at that point we’re just displaying the token itself and not any amount. This initially made me think that a value (like the amount I’d receive) was going to appear there. Since nothing actually shows up, I think it might be better to remove the divider for the destination token to avoid any confusion.
2. I also noticed that the fee UI appears even before a destination token is selected. This can make the UI feel a bit off and harder to understand, especially when the token selection menu is still open. I think it would be a smoother experience if we waited for the destination token to be selected before showing the fee-related info.
Let me know …

Conditional dividers in UI and wait for destination token

---

app/src/utils/token.ts

Removes sentry capture if a token is not found via multilocation. Which means we do not support it via our registry.

fix: remove sentry capture

---

app/src/components/Transfer.tsx

This small PR fixes the issue of showing a wrong origin banner on a swap

fix: wrong origin chain banner

---

app/src/components/Transfer.tsx
app/src/components/completed/TransactionHistory.tsx
app/src/components/completed/TransactionLoaderSkeleton.tsx

On mobile viewports between roughly 425 px and 600 px wide, switching from the “New” tab to the “Done” tab causes the app’s main container to shrink. This sudden width change makes the UI feel jumpy and cramped, especially in the “Done” view. This PR fix that.

Enhance responsive styling for full-width components

---

app/src/components/ChainTrigger.tsx
app/src/components/VerticalDivider.tsx
app/src/hooks/useTransferForm.ts

Fixes https://linear.app/velocitylabs/issue/VEL-393/bug-manual-recipient-issue-when-updating-a-source-token
We can decide to keep it if the new source+dest chains are compatible but let's keep it simple for now
https://github.com/user-attachments/assets/276f0d02-46cb-46d9-a6a5-e6350434f4da
https://github.com/user-attachments/assets/89f94fef-4f60-41ec-9ad4-49c96d029e3a

Fix UX when changing source chain/token with a manual recipient set

---

app/next.config.mjs
app/src/components/completed/TransactionHistory.tsx
app/src/components/ongoing/OngoingTransfers.tsx
app/tsconfig.json
packages/registry/src/index.ts
packages/ui/package.json
packages/ui/src/components/Button.tsx
packages/ui/src/components/TokenLogo.tsx

The transfers are being saved with the entirety of the Chain and/or Token in the storage itself – this is an issue, especially for images that might change paths (like logoURI). Therefore now we map the Chain (or Token) to the registry where the most up-to-date information relies. 
It's not the ideal solution because I would like the mapping to happen on a higher level, but for the sake of being quick this is a good short term fix. I would need to investigare more on how the transfers are mapped in the first, but I feel it would be a potential breaking change rn which is out of scope.

Fix logos not showing in Ongoing and Completed transfers

---

analytics/src/utils/validate-request.ts

We don't need this logic because the browser is already validating CORS.

Fix: Simplify request validation logic.

---

app/src/hooks/useParaspellApi.ts

DryRun & ED are preventing transfers from being made when not successful. 
It means that a chain like Centrifuge or Acala, which do not support DryRun in their runtime, can't be used. 
This PR fixes it and throws warning notifications instead of errors. 
UI/X could be updated - this is a hotfix.

hotfix: DryRun and ED verification errors handling 🔥

---

app/src/hooks/useParaspellApi.ts

This PR introduces a mechanism to identify chains that are failing during DryRun and logs these instances as warnings in Sentry. This will help us start pinpointing these chains and provide a clearer understanding of which ones are failing.

Chore: add exception capturing for dry-run validation errors

---

packages/registry/src/mainnet/chains.ts

We recieved another email asking to update the URL

Chore: Update Phala RPC connection URL

---

analytics/src/app/actions/summary.ts
analytics/src/components/TransactionChart.tsx

This PR changes the type of graph displayed on the dashboard for cumulative volume and the number of transactions. We are switching from an area graph to a more common and understandable bar graph. Additionally, we are excluding the current day and month from the data to prevent the graph from showing a downward trend when there isn't enough information available.

Impr: Replace AreaChart with BarChart

---

app/src/components/TransferEstimate.tsx
app/src/components/ongoing/OngoingTransfers.tsx
app/src/hooks/useChainflipApi.ts
app/src/hooks/useChainflipTracker.ts
app/src/hooks/useOngoingTransfers.ts
app/src/hooks/useTransferProgress.ts
app/src/models/transfer.ts
app/src/store/ongoingTransfersStore.ts
app/src/utils/chainflip.ts
app/src/utils/transfer.ts

This PR handles tracking a transfer from Ongoing to Completed:
✅ Implements Chainflip swaps tracking (`useChainflipTracker()` hook)
✅ Gets the [Chainflip explorer](https://scan.chainflip.io/swaps)
✅ Add swap to analytics with `trackTransferMetrics()` & `updateTransferMetrics()`
✅ Updates progress bar status. It introduces a 1.5-second timeout to complete the progress bar to 100%.
Closes [VEL-445](https://linear.app/velocitylabs/issue/VEL-445/chainflip-swap-tracking-explorer-links-metrics-support-and-progressbar)

Feat: chainflip/tracks swap, gets explorer, adds to metrics, & updates progress bar

---

app/src/components/Transfer.tsx
app/src/hooks/useChainflipQuote.ts
app/src/utils/chainflip.ts

Fix glitch (introduced after the new Tx Summary) when Chainflip fees are loading.
Closes [VEL-496](https://linear.app/velocitylabs/issue/VEL-496/chainflip-fix-ui-glitch-when-fees-are-loading)

fix: Chainflip loading fee UI glitch

---

app/src/hooks/useFees.ts
app/src/models/transfer.ts

- Adds the local transfer fee ETH > ETH Chainflip deposit address, and AH > AH Chainflip deposit address
- Fetches fees and, adds it to the fee array
- Verifies balance against this fee
Closes [VEL-493](https://linear.app/velocitylabs/issue/VEL-493/chainflip-update-usefees-to-handle-local-transfer-to-deposit-address)

feat: implement local transfer fees to Chainflip deposit address

---

app/src/hooks/useTransferForm.ts

Max amount `btn` requires tweaking the `destination chain` & the `recipient` to match the local transfer expected params.
Closes [VEL-508](https://linear.app/velocitylabs/issue/VEL-508/fix-assethub-max-amount-for-chainflip-swaps)

Fix: AH max button for Chainflip Swaps

---

app/src/utils/transfer.ts

This PR prevents `isNaN` error in `safeConvertAmount(sourceTokenAmount, sourceToken)`. 
⚠️ Can't reproduce the [Sentry related error](https://velocity-labs.sentry.io/issues/64113211/?project=4507345235345488&referrer=github-pr-bot)
Closes [VEL-507](https://linear.app/velocitylabs/issue/VEL-507/investigates-and-fix-usefees-isnan)

Fix: Add guards to safeConvertAmount in useFees

---

package.json
scripts/clean.sh

This script should be run whenever packages need to be built or new dependencies installed. It is especially useful for monorepo preparation, as it installs everything cleanly from scratch to ensure the setup works correctly.

Chore: Add cleanup script and new `clean` command in package.json

---

.changeset/social-mangos-itch.md
app/src/hooks/useChainflipApi.ts
app/src/hooks/useParaspellApi.ts
app/src/utils/transfer.ts
widget/src/hooks/useParaspellApi.tsx
widget/src/utils/transfer.ts

After the recent PAPI version upgrade, the `txHash` is not correctly cast as a hex string but is registered as a Uint8Array.
This PR addresses it by leveraging `Viem.js` instead of PAPI, as it does not provide any direct helper. 
🔥 Hotfix

Fix: txhash format tohex

---

.changeset/long-windows-help.md
widget/src/hooks/useOngoingTransfersTracker.ts
widget/src/models/transfer.ts
widget/src/utils/tracking.ts

Widget hooks compliance & SnowBridge tracking rely on the app history API route.
⚠️ fetch request endpoint must be updated when CORS issue are fixed.
WIP - App migration to Widget

feat: widget rely on history api route for SB tracking
