velocitylabs-org/turtle

app/.eslintrc.json
app/.husky/pre-commit
app/.prettierignore
app/.prettierrc
app/jest.config.ts
app/next.config.mjs
app/package-lock.json
app/package.json
app/postcss.config.mjs
app/sentry.client.config.ts
app/sentry.edge.config.ts
app/sentry.server.config.ts
app/src/app/api/sentry-example-api/route.js
app/src/app/global-error.tsx
app/src/app/globals.css
app/src/app/layout.tsx
app/src/app/page.tsx
app/tailwind.config.ts

This PR updates the turtle configurations. I now switched from working on my fork to working directly in the original repo
- update prettier config and format rules
- format many files with new prettier settings
- add eslint tsdoc support
- add eslint prettier support
- install and configure jest
- add husky and run prettier and lint as pre-commit

update project configs

---

app/package.json
app/pnpm-lock.yaml
app/public/notification-default-icon.svg
app/public/notification-error-icon.svg
app/public/notification-info-icon.svg
app/public/notification-success-icon.svg
app/public/notification-warning-icon.svg
app/src/app/layout.tsx
app/src/components/Notification.tsx
app/src/components/NotificationSystem.tsx
app/src/components/NotificationToast.tsx
app/src/hooks/useNotification.tsx
app/src/models/notification.ts
app/src/store/notificationStore.ts

This PR
- adds Zustand as a state management that globally stores notifications
- adds notification model, notification component, and a notification hook
- adds support for different notification severities (default, warning, info ...) that change the icon and background color. Also notifications support a header and a message.
- adds smooth fading in and out animations to the notifications

Adds notifications to the app

---

app/next.config.mjs

This tiny PR just changes the sentry config and hopefully fixes our vercel deployment.

changes sentry configs

---

app/package.json
app/pnpm-lock.yaml
app/src/app/layout.tsx
app/src/utils/wallet.ts

This small PR adds vercel analytics.
And adds a small cleanup.

Integration 🐢 add vercel analytics to the app

---

app/src/components/NavBar.tsx

This tiny PR adds an alpha banner.

🌱 feat: add alpha banner

---

app/src/components/Button.tsx
app/src/components/ChainSelect.tsx
app/src/components/OngoingTransfer.tsx
app/src/components/OngoingTransferDialog.tsx
app/src/components/TokenAmountSelect.tsx
app/src/components/Transfer.tsx
app/src/hooks/useTransfer.tsx

This PR
- adds border around tokens/chains
- removes undesired blue ring around buttons on tab focus
- fixes layout issues
- fix eslint warnings
- adds form reset on successful transfer initiation. And scrolls to bottom where the transfer is shown!

feat: flow improvements and small changes

---

app/src/config/registry.ts
app/src/hooks/useErc20Balance.tsx
app/src/hooks/useTransfer.tsx
app/src/hooks/useTransferForm.tsx
app/src/services/balance.ts

- fix weth address
- add more error handling
- change balance fetching logic a bit

hotfix: wrong registry entry

---

app/src/components/Dropdown.tsx
app/src/components/FeesPreview.tsx
app/src/components/Transfer.tsx

- To the Select components
- To the fees preview

feat: adds spring animations

---

app/src/components/ChainSelect.tsx
app/src/components/Transfer.tsx
app/src/hooks/useTransfer.tsx
app/src/hooks/useTransferForm.tsx

- rewrites useTransfer. Please thoroughly check as our functionality depends on it.
- fix smaller issues. Show fees only on valid input, fix reset issues after transfer complete
- improve error handling

🪸 refactor useTransfer and fix issues 

---

app/src/app/globals.css
app/src/components/Credits.tsx
app/src/components/Transfer.tsx

This PR
- fixes up and down arrows on firefox
- refactors credits component
- removes some warnings

fix: some minor issues

---

app/package.json
app/pnpm-lock.yaml
app/src/config/registry.ts

- Please double check that I added it correctly [here](https://github.com/Snowfork/snowbridge/blob/main/web/packages/api/src/environment.ts)

feat: extend registry by usdc, usdt and dai

---

app/src/utils/transfer.ts

Update the explorer links. 
Note: Polkadot one can't be tested on testnet as it's still broken.

update explorer url

---

app/src/hooks/useSnowbridgeTransferTracker.tsx

This PR
- removes unnecessary history fetches

fix: improve status tracking performance

---

.github/workflows/lint.yml

The .github folder must be in root of our repo. This PR fixes this.

fix: github action directory

---

README.md

feat: readme addition

---

app/.env.local.example
app/src/context/snowbridge.tsx

- adds private endpoints for assethub, bridgehub and relaychain

fix: add custom rpc endpoints on mainnet

---

app/src/components/ChainSelect.tsx
app/src/components/SubstrateWalletModal.tsx
app/src/components/WalletButton.tsx
app/src/components/WalletNotAccessible.tsx
app/src/utils/env.ts

This PR adds the WalletNotAccessible component on Talisman Connect on Devices. 
Note: It does not any more rely on Tailwind LG breakpoint but on userAgent native web API.

feat: mobile connection not working note

---

app/src/hooks/useErc20Allowance.tsx
app/src/hooks/useTransfer.tsx
app/src/utils/analytics.ts

This PR
- Adds vercel and sentry metrics. We can decide what we like more in the future.
- Adds some cleanup and improves error handling. Removes raised sentry issues on user tx rejection.

feat: add metrics

---

app/src/config/registry.ts
app/src/hooks/useTransfer.tsx
app/src/models/chain.ts

Add parachain destination fee to Registry + integrate

feat: add parachain destination fees

---

app/.env.local.example
app/src/config/registry.ts

Feat: extend parachains registry

---

app/src/app/error.tsx
app/src/app/global-error.tsx
app/src/app/globals.css
app/src/app/layout.tsx
app/src/app/not-found.tsx
app/src/components/Menu.tsx
app/src/components/NavBar.tsx
app/src/components/OngoingTransfer.tsx
app/src/components/OngoingTransferDialog.tsx
app/src/components/OngoingTransfers.tsx
app/src/components/completed/TransactionCard.tsx
app/src/components/completed/TransactionDialog.tsx
app/src/components/completed/TransactionHistory.tsx
app/src/components/completed/TransactionLoaderSkeleton.tsx
app/src/components/ui/button.tsx
app/src/components/ui/dialog.tsx

fix: Set letter-spacing according to the Figma design spec

---

app/src/utils/filters.ts

Implementation of the chains transfer filters (source chains, dest chains, tokens).
Now implementing isRouteAllowed filter and implementing it in chain swap.

update chain filters

---

app/src/components/ChainSelect.tsx
app/src/components/TokenAmountSelect.tsx
app/src/components/Transfer.tsx
app/src/models/select.ts

- disable chains and tokens based on allowed routes
- disable form inputs so users must start with source chain
Future tasks
- order chains and tokens
- make swap work properly (Victor works on this)

feat: ⭐ visualize filtered dropdown

---

app/src/components/TokenAmountSelect.tsx
app/src/hooks/useTransferForm.tsx
app/src/utils/filters.ts

This PR
- adds chain and token ordering based on routes
- resets dest and token on source chain change
- fixes issue of token deselect on swap
- adds some cleanups

feat: adapt ui to routes

---

app/src/components/SwapFromToChains.tsx
app/src/components/svg/Swap.tsx
app/src/hooks/useTransferForm.tsx
app/src/utils/filters.ts

This PR is marked as a draft since we want this [PR](https://github.com/velocitylabs-org/turtle/pull/113) to be merged first: 
- fixes some react SVG alert
- refactors/simplifies the isRouteAllowed.

Fix: is route allowed refactor

---

app/src/components/SwapFromToChains.tsx
app/src/components/Transfer.tsx
app/src/utils/filters.ts

- Fixes the case where destination is changed but tokens are not updated
- Fixes double clicking the swap button from selecting the text

fix: ⭐ token list update on dest chain switch

---

app/src/components/SwapFromToChains.tsx
app/src/components/Transfer.tsx
app/src/hooks/useTransferForm.tsx

This PR prevent chains swap when a transfer is ongoing and updates CSS accordingly.

Fix: prevents swap when transfer is ongoing

---

app/src/config/registry.ts

Fixed https://linear.app/velocitylabs/issue/VEL-84/fix-update-asset-hub-logo. 
I still code 👋

fix: Use correct AssetHub logo

---

app/src/components/Transfer.tsx

This PR adds a simple loading placeholder if the balance is fetching

feat: Add loading balance indicator

---

site/src/components/TurtlesBackground.tsx
site/src/components/card.tsx
site/src/components/features.tsx
site/tailwind.config.ts

Fixes https://github.com/velocitylabs-org/turtle/issues/109. As well as the word break issue @brandonhaslegs reported.
https://github.com/user-attachments/assets/f857e53a-5325-4686-802c-38b98c8362d7

Fix landing page text styling

---

app/src/components/OngoingTransferDialog.tsx
app/src/components/completed/TransactionDialog.tsx

Fixes https://github.com/velocitylabs-org/turtle/issues/93.

Show $ sign before USD amount

---

app/src/components/ChainSelect.tsx
app/src/components/OngoingTransfer.tsx
app/src/components/OngoingTransferDialog.tsx
app/src/components/TokenAmountSelect.tsx
app/src/components/completed/TransactionCard.tsx
app/src/components/completed/TransactionDialog.tsx

Closes https://github.com/velocitylabs-org/turtle/issues/94
NB: I didn't visually check all the instances that I changed. We should think about visual regression tests for the app.

fix: Add a background color to all avatars

---

app/src/utils/transfer.ts

This tiny PR: 
- Fix - AH to ETH explorer link => now displays `extrinsic`
- Improve the default explorer link within the Polkadot environment to display all `XCM transfers`

improvement: update explorer links

---

app/src/components/ChainSelect.tsx

Closes https://github.com/velocitylabs-org/turtle/issues/97

feat: Add ENS avatar to chain selector

---

app/.env.local.example
app/CONTRIBUTING.md
app/src/app/api/history/route.ts
app/src/app/layout.tsx
app/src/components/completed/TransactionDialog.tsx
app/src/config/index.tsx
app/src/context/index.tsx
app/src/context/snowbridge.tsx
app/src/hooks/useEnvironment.tsx
app/src/hooks/useOngoingTransfersTracker.tsx
app/src/hooks/useSnowbridgeContext.tsx
app/src/store/environmentStore.ts

- let's us specify the environment via env variables now
- adds the groundwork to support switching environments inside the app in the future

refactor: config

---

app/src/config/registry.ts

This small PR changes some registry logo urls to more reliable sources. 
And fixes the wrong WETH logo we used.

⚡ improvement: registry logo urls

---

app/src/hooks/useParaspellApi.tsx
app/src/utils/polkadot.ts

A little fix that should support finding the messageHash with x-tokens pallet.

fix: 🔍 get message_hash from UpwardMessageSent extrinsic

---

app/.env.local.example
app/CONTRIBUTING.md
app/src/config/registry.ts
app/src/context/snowbridge.tsx
app/src/models/chain.ts
app/src/models/schemas.ts

- restructure env -> After merging we need to have a new env file
- add many chains to the registry

feat⚡extend registry by parachains

---

app/pnpm-lock.yaml
app/src/config/registry.ts

✅ Tested a wETH transfer on Mainnet. The tokens landed as expected on the destination account on Moonbeam.

feat: Support Ethereum -> Moonbeam for wETH+wBTC

---

app/src/hooks/useTransferForm.tsx

- fixes rpc error [VEL-104](https://linear.app/velocitylabs/issue/VEL-104/bug-rpc-error-on-swap-chains-spam)

fix: remove unused papi code

---

app/src/components/OngoingTransferDialog.tsx
app/src/config/registry.ts

Added routes 🚀 
- Moving DOT from RC to Hydration, Moonbeam, Interlay, Acala, Centrifuge, Astar, Bifrost
- Moving DOT from Hydration, Bifrost, Acala to RC
- routes are tested and working
Not working routes 🕵️ 
- Moving DOT from Moonbeam, Centrifuge, Astar to Relay. It fails to fetch balance, we need to investigate. Maybe local asset id will help.
- These are not included in this PR so we can do it in a seperate one

feat 💫 add new routes

---

app/src/config/registry.ts

Add both Native USDC and USDT stablecoins. 
Tested on AH <=> Bifrost.

feat: add Native USDC and USDT stablecoins

---

app/src/components/Transfer.tsx
app/src/components/TxSummary.tsx
app/src/hooks/useTokenPrice.tsx
app/src/hooks/useTransferForm.tsx
app/src/services/balance.ts

1. Refactor `useTokenPrice` hook to handle loading state.
2. Move `useTokenPrice` call from `useTransferForm` to `TxSummary` component
3. Improve `TxSummary` conditional rendering when both token & token amount are selected
4. Add _Skeletion_ when the token price is loading and prevent failed price fetch to block transfer

improvement: update token price fetch and tx summary

---

app/package.json
app/pnpm-lock.yaml
app/src/registry/mainnet.ts

This PR contains: 
A registry update with Interlay - Hydration xcm priority transfers.
Paraspell SDK upgrade.

feat: add Interlay - Hydration xcm transfers

---

app/src/components/Transfer.tsx
app/src/components/TxSummary.tsx

Fix flow when the form is valid but Tx Summary is not displayed.

fix: tx summary displaying flow

---

app/package.json
app/pnpm-lock.yaml
app/src/app/globals.css
app/src/components/Button.tsx
app/src/components/HomeComponentSelect.tsx
app/src/components/Menu.tsx
app/src/components/NotificationToast.tsx
app/src/components/OngoingTransfers.tsx
app/src/components/SendButton.tsx
app/src/components/Transfer.tsx
app/src/components/TxSummary.tsx
app/src/hooks/useOngoingTransfers.tsx
app/src/hooks/useOngoingTransfersTracker.tsx
app/src/hooks/useParaspellApi.tsx
app/src/hooks/useSnowbridgeApi.tsx
app/src/hooks/useTransfer.tsx
app/src/hooks/useTransferForm.tsx
app/src/models/transfer.ts
app/src/store/ongoingTransfersStore.ts
app/tailwind.config.ts

- Morph the `SendButton` to show status updates
- When sending an XCM, move the tx to 'ongoing' as soon as possible 
- Lots of (hopefully) improvements

ux: Improve XCM tx send flow

---

app/src/hooks/useTransferForm.tsx

A small fix to solve the route bypass.

fix route bypass

---

app/src/app/globals.css
app/src/components/Credits.tsx

Note: we definitely don't have to go with this rainbow tweak of mine - I just tried it out since that we now have the credits in two lines and with more text, which makes it heavier. By adding some color it makes it cooler and lighter but that's just my quick impression.

Add `ParaSpell` to the credits

---

app/src/components/TxSummary.tsx

Little commit/PR: I removed the NumberFlow animation from the TxSummary fees

fix: tx summary fees format

---

app/src/components/SwapFromToChains.tsx

Change naming from "Swap" to "Switch"

---

app/public/logos/novawallet.svg
app/src/components/SubstrateWalletModal.tsx
app/src/components/WalletButton.tsx
app/src/hooks/useSubstrateWallet.tsx
app/src/utils/wallet.ts

Fixes that connect button doesn't work on Nova wallet browser.

hotfix: Substrate connect button on mobile

---

app/src/context/index.tsx

This PR fixes an issue in the Appkit configs.

fix: remove redundant wagmiAdapter

---

app/src/components/SubstrateWalletModal.tsx
app/src/components/TokenAmountSelect.tsx

Fix 
- Substrate Modal mobile responsive
- Form mobile responsive
Please give it a try as my iPhone is too big to display the white border: 
https://turtle-app-git-fix-responsive-form-velocity-labs.vercel.app/

fix: responsive design improvements

---

app/package.json
app/pnpm-lock.yaml
app/src/registry/mainnet.ts

Tested and working perfectly ✅

flow: Support native USDC between Centrifuge <> AH

---

app/src/components/Switch.tsx

Add forwardRef to Switch to fix the log error. 
[Part of this issue. ](https://linear.app/velocitylabs/issue/VEL-122/fix-nextjs-component-error-log)

fix: react/add forwardRef to Switch

---

app/src/components/ChainSelect.tsx
app/src/components/TokenAmountSelect.tsx

Easy fix for this [issue](https://linear.app/velocitylabs/issue/VEL-194/filter-out-unsupported-tokens-instead-of-disabling-them)! 
=> Filter out unsupported tokens instead of disabling them

fix: remove not allowed tokens from list

---

app/src/utils/paraspell.ts

Temp solution to fix sentry errors that occur in production.

hotfix: add fallback to getTokenSymbol function

---

app/src/hooks/useFees.tsx

This PR potentially fixes an issue causing `snowbridgeContext` to be undefined in certain cases.
[Sentry Issue](https://velocity-labs.sentry.io/share/issue/1b28068884d14e5481ab0da75e67c323/)

fix: snowbridge context undefined error

---

app/src/registry/mainnet/routes.ts

Disables some moonbeam routes that we are currently fixing and make work.

hotfix: temp disable some routes

---

app/src/registry/mainnet/routes.ts

Enables to move MYTH between AH and Mythos.

feat: add AH - Mythos routes

---

app/package.json
app/pnpm-lock.yaml
app/src/registry/mainnet/routes.ts

Upgrade PS SDK and add moonbeam routes back. 
=> Balance fetches correctly now.

fix: moonbeam balances

---

app/src/registry/mainnet/routes.ts

Allows to move MYTH between Hydra and Mythos

feat ⭐ add mythos - hydra route

---

app/src/registry/mainnet/routes.ts

Disable Myth from Eth to Asset Hub. 
(Waiting for Nico to confirm before merging)

fix: removed Myth from ETH to AH

---

app/src/hooks/useTransferForm.tsx
app/src/utils/routes.ts

This PR prevents users from bypassing chain/token selection.

fix: prevent bypass route selection

---

app/src/components/TokenAmountSelect.tsx

improvement: add compact notation to usd value

---

app/package.json
app/pnpm-lock.yaml

fixes AH to Mythos fees fetching.

hotfix: update PS version to 8.1.0

---

app/src/utils/paraspell.ts

fix: moonbeam xc token symbol issue

---

app/src/components/TokenAmountSelect.tsx

Colors the selected token background.

fix: selected token background

---

app/src/registry/mainnet/chains.ts
app/src/registry/mainnet/mainnet.ts
app/src/registry/mainnet/routes.ts
app/src/registry/mainnet/tokens.ts

- add polimec chain and PLMC token
- add routes to/from AH with tokens DOT, USDT, USDC

feat: add polimec routes

---

app/src/components/Transfer.tsx
app/src/hooks/useTransferForm.tsx

This PR fixes the issue that the send button is not enabled in some cases.

fix: disabled send button

---

app/src/hooks/useOngoingTransfersTracker.tsx

Converts Bigint to string to fix storing the completed transfers.

fix: completed transfers storage

---

app/src/components/SubstrateWalletModal.tsx
app/src/utils/wallet.ts

improvement: add wallet extension weights

---

app/pnpm-lock.yaml
app/src/hooks/useFees.tsx
app/src/hooks/useTransferForm.tsx
app/src/utils/snowbridge.ts

Basically only fetch when all inputs are ready. More improvements to come

hotfix: Fix sb fee fetching issues

---

app/src/components/ActionBanner.tsx
app/src/components/Button.tsx
app/src/components/ChainSelect.tsx
app/src/components/TokenAmountSelect.tsx
app/src/components/Transfer.tsx
app/src/components/TxSummary.tsx
app/src/components/WalletButton.tsx
app/src/hooks/useFees.tsx

A bunch of small tweaks making the UI more pleasant and responsive on small screens

Improve UI responsiveness on mobile

---

app/src/hooks/useBalance.tsx
app/src/hooks/useFees.tsx
app/src/utils/paraspell.ts

This PR
- Adds the function getParaspellToken that relies primarily on multilocations to map turtle tokens to paraspell tokens
- Has a fallback to token symbol
- Contains edge cases that are in development by paraspell

improvement: Paraspell token mapping

---

widget/README.md
widget/src/components/Button.tsx
widget/src/components/ChainSelect.tsx
widget/src/components/TokenAmountSelect.tsx
widget/src/components/Transfer.tsx
widget/src/components/Widget.tsx
widget/src/components/history/HistoryLoaderSkeleton.tsx
widget/src/components/history/TransfersHistory.tsx
widget/src/components/history/completed-transfers/Card.tsx
widget/src/components/history/completed-transfers/Dialog.tsx
widget/src/components/history/ongoing-transfers/Card.tsx
widget/src/components/history/ongoing-transfers/Dialog.tsx
widget/src/components/ui/button.tsx
widget/src/components/ui/dialog.tsx
widget/src/index.css
widget/src/index.ts
widget/src/registry/mainnet/chains.ts
widget/src/utils/theme.ts
widget/tailwind.config.ts

This PR: 
- updates some css variables' names to match the theme
- updates tailwind.config to support css root variables
- implements a `generateWidgetTheme()` helper with types
- implements the MVP Documentation inside the Widget Readme
_(also included a random Registry update)_
This should be kept in mind

feat: 🎨 implement customizable theme

---

app/src/components/OngoingTransferDialog.tsx
app/src/components/completed/TransactionDialog.tsx
app/src/components/completed/TransactionHistory.tsx

Updated OngoingTransferDialog and TransactionDialog to deliver a more compact UI that occupies less space and adapts better for animations transitioning from cards.

Refactor Dialogs/Modals for a more Compact Interface

---

app/src/models/transfer.ts
app/src/store/completedTransfersStore.ts
app/src/store/ongoingTransfersStore.ts

This PR
- Refactors the ongoing transfer store
- Adds versioning and migration functions to ongoing and completed transfers
- enables backwards compatibility with the version before swaps are introduced

feat: add storage versioning and version migrations

---

app/src/components/completed/TransactionCard.tsx
app/src/components/completed/TransactionDialog.tsx
app/src/components/ongoing/OngoingTransferDialog.tsx

Adjusted hover text color in `TransactionCard` for better contrast. Updated `TransactionDialog` messages to include timestamps and ensure proper alignment and readability.

Small UI fixes to completed TX card and modal

---

app/src/components/SubstrateWalletModal.tsx
app/src/components/ui/dialog.tsx

Introduce additional props to DialogContent for greater flexibility, including overlay and close button customization. Update SubstrateWalletModal styling, layout, and interactive states for improved usability and visual consistency.

Update SubstrateWalletModal to look like ETH based modal wallet

---

app/src/hooks/useFees.ts
app/src/hooks/useOutputAmount.tsx
app/src/hooks/useTransferForm.ts
app/src/utils/transfer.ts

This PR adds the receive amount also for transfers. It deducts the fees if there are some.

impr: show receive amount for transfers

---

app/src/registry/mainnet/routes.ts

Polimec <> Hydration DOT, USDC, USDT

Add routes between Polimec and Hydration in mainnet registry

---

app/src/components/ChainTokenSelect.tsx
app/src/components/ChainTrigger.tsx

This PR fixes the cursor on the inputs

fix: clickable area for dropdown

---

app/src/components/SubstrateWalletModal.tsx

This PR refactors the SubstrateWalletModal animations to better align with the look and feel of the Ethereum base modal. The changes are purely UI-related, focusing on animations and visual elements only.

Refactor SubstrateWalletModal animations

---

app/src/components/completed/TransactionCard.tsx
app/src/components/ongoing/OngoingTransfer.tsx

This PR adjusts the ongoing and completed transfer cards. It shows now only the receiving token.

impr: adjust swaps ui to work on mobile

---

app/src/hooks/useTransferForm.ts

In [yesterday's PR ](https://github.com/velocitylabs-org/turtle/pull/361), this logic needed to be refactored as well. Doing it now.

Fix: Refactor fee calculation logic in setTransferableBalance

---

app/src/components/SubstrateWalletModal.tsx

Tiny PR to support substrate ed25519 account. 
Tested by Leonard from Polimec with the preview.

impr: add substrate ed25519 account support

---

app/src/registry/mainnet/mainnet.ts
app/src/registry/mainnet/routes.ts
app/src/registry/mainnet/tokens.ts
pnpm-lock.yaml

Support MYTH transfers between Mythos and AssetHub

---

app/src/hooks/useParaspellApi.ts

This PR fixes an issue that we forgot to check for extrinsic success event. And it adds notifications for the user that we forgot.

impr: add extrinsic success check and swap notifications

---

.github/workflows/release.yml

added github action
https://linear.app/velocitylabs/issue/VEL-439/automate-versioning-cycle-for-changing-packages

Automate versioning cycle for changing packages

---

site/src/components/AnalyticData.tsx
site/src/utils/fetchAnalyticsData.ts

There is a new specification detailing how the landing volume component should look [Figma](https://www.figma.com/design/jhzo7cXOW2DxTgUwlIEG1L/%F0%9F%90%A2-Turtle---Raissa?node-id=65-11&p=f&m=dev)

Refactor: Simplify UI of Total Volume Display on Landing Page

---

HOW_TO_TURBO.md

Added HOW_TO_TURBO.md file 
https://linear.app/velocitylabs/issue/VEL-416/step-by-step-tutorial-for-creating-packages

step-by-step tutorial for creating packages

---

.changeset/happy-pots-sit.md
packages/assets/logos/chainlink.svg

This PR updates the Chainlink logo to improve its appearance, colors, and dimensions.

Update: Revamp Chainlink logo with new dimensions and background

---

.changeset/hot-shirts-sneeze.md
widget/src/components/ChainflipRefund.tsx
widget/src/components/Transfer.tsx
widget/src/components/TxSummary.tsx
widget/src/components/history/completed-transfers/Dialog.tsx
widget/src/components/history/ongoing-transfers/Dialog.tsx
widget/src/hooks/useBalance.ts
widget/src/hooks/useChainflipApi.ts
widget/src/lib/paraspell/transfer.ts
widget/src/models/schemas.ts
widget/src/store/ongoingTransfersStore.ts
widget/src/utils/tracking.ts
widget/src/utils/transfer.ts

Widget compliance: Complete Chainflip w Arbitrum implementation
WIP - App migration to Widget

feat: Complete Chainflip w Arbitrum implementation in the Widget

---

app/src/components/AppHome.tsx
pnpm-lock.yaml
scripts/clean.sh

This PR fixes the clean script, adding the widget install and also includes a try-catch block in case it fails. If it fails the first time running it, a second attempt will resolve the issue.

Feat: Add retry logic and improve cleanup process in `clean.sh` script
